export enum Institution {
    CNB = "Česká národní banka",
    AB = "Air Bank",
    BC = "Banka Creditas",
    CEB = "Česká exportní banka",
    CS = "Česká spořitelna",
    CSS = "Českomoravská stavební spořitelna",
    CZaRB = "Českomoravská záruční a rozvojová banka",
    CSOB = "Československá obchodní banka",
    EB = "Equa bank",
    ECZ = "Expobank CZ",
    FB = "Fio banka",
    HB = "Hypoteční banka",
    JaTB = "J&T Banka",
    KB = "Komerční banka",
    MMB = "Moneta Money Bank",
    MPSS = "Modrá pyramida stavební spořitelna",
    PFFB = "PPF Banka",
    RSS = "Raiffeisen stavební spořitelna",
    RCZ = "Raiffeisenbank (Czech Republic)",
    SCZ = "Sberbank CZ",
    SSCS = "Stavební spořitelna České spořitelny",
    UBCZaSK = "UniCredit Bank Czech Republic and Slovakia",
    WSP = "Wüstenrot - stavební spořitelna",
    WHB = "Wüstenrot hypoteční banka"
}